# Basic
title: echochio
subtitle: 
description: 歡迎來到我的部落格
# 头像里面的标题
avatarTitle: echochio
# 头像里面的描述
avatarDesc: 紀錄一些雜七雜八的技術
url: "https://www.echochio.nctu.me"

# Comment
comment:
    # disqus: leopard
# duoshuo: echochio
    uyan:2128926

# Social
social:
    # weibo: www.echochio.nctu.me
    github: echochio-tw
    # twitter: 
    mail: chio@echochio.nctu.me

# 百度统计 
# 使用博客模板请去掉或者更换 id 
#baidu:
#   id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-108823459-2   
    host: auto  


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 部落格主頁

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 標籤, description: tags, url: '/tags'}      
    - {title: 關於我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
plugins:
          - jekyll-paginate
paginate: 5
